apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-config
  namespace: fcg
data:
  ASPNETCORE_URLS: http://+:8080
  RabbitMq__Host: rabbitmq
  RabbitMq__OrderQueue: payments-orders
  Payments__AlwaysApprove: "true"
